default: all
Q0 : Q0.c
	gcc -g -Wall -std=c99 -o Q0 Q0.c -Wall -Werror
Q1 : Q1.c
	gcc -g -Wall -std=c99 -o Q1 Q1.c -Wall -Werror
Q2 : Q2.c
	gcc -g -Wall -std=c99 -o Q2 Q2.c -Wall -Werror
Q3 : Q3.c
	gcc -g -Wall -std=c99 -o Q3 Q3.c -Wall -Werror
Q4 : Q4.c
	gcc -g -Wall -std=c99 -o Q4 Q4.c -Wall -Werror
Q5 : Q5.c
	gcc -g -Wall -std=c99 -o Q5 Q5.c -Wall -Werror
all:
	gcc -g -Wall -std=c99 -o Q0 Q0.c -Wall -Werror
	gcc -g -Wall -std=c99 -o Q1 Q1.c -Wall -Werror
	gcc -g -Wall -std=c99 -o Q2 Q2.c -Wall -Werror
	gcc -g -Wall -std=c99 -o Q3 Q3.c -Wall -Werror
	gcc -g -Wall -std=c99 -o Q4 Q4.c -Wall -Werror
	gcc -g -Wall -std=c99 -o Q5 Q5.c -Wall -Werror

clean:
	rm Q0
	rm Q1
	rm Q2
	rm Q3
	rm Q4
	rm Q5
